services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch-node1
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health | grep -q '\"status\"'"]
      interval: 10s
      timeout: 5s
      retries: 30

  opensearch-node2:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch-node2
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health | grep -q '\"status\"'"]
      interval: 10s
      timeout: 5s
      retries: 30

  opensearch-node3:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch-node3
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node3
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    volumes:
      - opensearch-data3:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health | grep -q '\"status\"'"]
      interval: 10s
      timeout: 5s
      retries: 30

  opensearch-dash:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dash
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch-node1:9200","http://opensearch-node2:9200","http://opensearch-node3:9200"]
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      opensearch-node1:
        condition: service_healthy

  themis-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: themis-ai-api
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      - OPENSEARCH_HOST=http://opensearch-node1:9200
      - RELOAD=true
      - LLAMA_CPP_PATH=/app/llama.cpp/build/bin/llama-cli
      # opcional: modele o MODEL_PATH no .env.docker ou copie o .gguf p/ /models
      # - MODEL_PATH=/models/mistral-7b-instruct-v0.1.Q4_K_M.gguf
    depends_on:
      opensearch-node1:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app:delegated
      - models-data:/models
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:
  models-data:
