
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOST=http://opensearch:9200

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
